"""
Here are some examples of tests I should write:

- manually annotate which genes are in each test pathway and compare them with results

- download the pictures from kegg and compare them with the pictures generated by networkx

"""
